import { AssetList } from '@chain-registry/types';

import _agoricdevnet from './agoricdevnet';
import _akashtestnet from './akashtestnet';
import _archwaytestnet from './archwaytestnet';
import _axelartestnet from './axelartestnet';
import _babylontestnet from './babylontestnet';
import _celestiatestnet3 from './celestiatestnet3';
import _chain4energytestnet from './chain4energytestnet';
import _composabletestnet from './composabletestnet';
import _coreumtestnet from './coreumtestnet';
import _cosmoshubtestnet from './cosmoshubtestnet';
import _cosmosicsprovidertestnet from './cosmosicsprovidertestnet';
import _doravotatestnet from './doravotatestnet';
import _dydxtestnet from './dydxtestnet';
import _elystestnet from './elystestnet';
import _empowertestnet from './empowertestnet';
import _hippoprotocoltestnet from './hippoprotocoltestnet';
import _impacthubtestnet from './impacthubtestnet';
import _injectivetestnet from './injectivetestnet';
import _int3facetestnet from './int3facetestnet';
import _jackaltestnet2 from './jackaltestnet2';
import _kimanetworktestnet from './kimanetworktestnet';
import _kujiratestnet from './kujiratestnet';
import _kyvetestnet from './kyvetestnet';
import _lavatestnet from './lavatestnet';
import _likecointestnet from './likecointestnet';
import _manifesttestnet from './manifesttestnet';
import _mantrachaintestnet from './mantrachaintestnet';
import _mantrachaintestnet2 from './mantrachaintestnet2';
import _marstestnet from './marstestnet';
import _neutrontestnet from './neutrontestnet';
import _nobletestnet from './nobletestnet';
import _noistestnet from './noistestnet';
import _nolustestnet from './nolustestnet';
import _osmosistestnet from './osmosistestnet';
import _persistencetestnet2 from './persistencetestnet2';
import _sagatestnet from './sagatestnet';
import _seitestnet2 from './seitestnet2';
import _sgetestnet from './sgetestnet';
import _stargazetestnet from './stargazetestnet';
import _stridetestnet from './stridetestnet';
import _swisstroniktestnet from './swisstroniktestnet';
import _symphonytestnet from './symphonytestnet';
import _synternettestnet from './synternettestnet';
import _terra2testnet from './terra2testnet';
import _titannettestnet from './titannettestnet';
import _titantestnet from './titantestnet';
import _wardenprotocoltestnet from './wardenprotocoltestnet';
import _xiontestnet2 from './xiontestnet2';
import _xrplevmtestnet from './xrplevmtestnet'

const assets: AssetList[] = [_agoricdevnet,_akashtestnet,_archwaytestnet,_axelartestnet,_babylontestnet,_celestiatestnet3,_chain4energytestnet,_composabletestnet,_coreumtestnet,_cosmoshubtestnet,_cosmosicsprovidertestnet,_doravotatestnet,_dydxtestnet,_elystestnet,_empowertestnet,_hippoprotocoltestnet,_impacthubtestnet,_injectivetestnet,_int3facetestnet,_jackaltestnet2,_kimanetworktestnet,_kujiratestnet,_kyvetestnet,_lavatestnet,_likecointestnet,_manifesttestnet,_mantrachaintestnet,_mantrachaintestnet2,_marstestnet,_neutrontestnet,_nobletestnet,_noistestnet,_nolustestnet,_osmosistestnet,_persistencetestnet2,_sagatestnet,_seitestnet2,_sgetestnet,_stargazetestnet,_stridetestnet,_swisstroniktestnet,_symphonytestnet,_synternettestnet,_terra2testnet,_titannettestnet,_titantestnet,_wardenprotocoltestnet,_xiontestnet2,_xrplevmtestnet];

export default assets;
